spring:
  datasource:        
    driver-class-name: org.postgresql.Driver
    platform: postgres    
    url: jdbc:postgresql://localhost:5432/empresa
    username: postgres
    password: 1234    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true        
